name: flutter_starter
description: a starter base on myself project
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  flutter_riverpod: ^2.3.6
  flutter_easyloading: ^3.0.5
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.12
  logger: ^1.4.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  synchronized: ^3.1.0
  go_router: ^10.0.0
  alice: ^0.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # 待修改的图片路径
  min_sdk_android: 21 # android min sdk min:16, default 21


