name: flutter_starter
description: a starter base on myself project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  flutter_riverpod: ^2.3.6 # 状态管理
  riverpod_annotation: ^2.1.1
  flutter_easyloading: ^3.0.5 # 加载动画
  dio: ^5.2.1+1 # 网络请求
  pretty_dio_logger: ^1.3.1 # 网络请求日志
  pull_to_refresh: ^2.0.0 #下拉刷新
  url_launcher: ^6.1.11 #打开外部链接
  logger: ^1.4.0 #日志
  fluttertoast: ^8.2.2 #toast
  shared_preferences: ^2.0.6 #本地存储
  synchronized: ^3.0.0 #同步锁
  go_router: ^6.5.5 #路由



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner:
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

