name: flutter_starter
description: a starter base on myself project
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_riverpod: ^2.4.9
  flutter_easyloading: ^3.0.5
  dio: ^5.4.0
  flutter_local_notifications: ^16.3.2
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  package_info_plus: ^5.0.1
  easy_refresh: ^3.3.4
  url_launcher: ^6.2.4
  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  synchronized: ^3.1.0+1
  custom_refresh_indicator: ^3.0.0
  go_router: ^13.0.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_datetime_picker_bdaya: ^3.0.2
  dartx: ^1.2.0
  open_filex: ^4.3.4
  chopper: ^7.1.0+1
  collection: ^1.18.0
  share_plus: ^7.2.1
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  path: ^1.8.0

flutter:
  uses-material-design: true

#配置app的图标
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # 待修改的图片路径
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"


